
project_id = "xblaayhsnjenrvmmjqta"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]

[storage]
enabled = true

[storage.buckets.service-photos]
public = true
file_size_limit = 10485760
allowed_mime_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]

[functions.generate-and-send-report]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
