// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xblaayhsnjenrvmmjqta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibGFheWhzbmplbnJ2bW1qcXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzkzODMsImV4cCI6MjA2NDg1NTM4M30.BdYNU1Xt0vtQWyNODMfbnmC89h_tgo2zYXHdfgfquYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);